spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info
    password: H9MvYSqY3JmAC4aj
    username: root
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        max-wait: 30000
        min-idle: 0

server:
  servlet:
    context-path: /api/v1
  port: 8080

qsbk:
  login:
    enable-sms: true
    expire-in: 60
  token:
    expire-in: 30000

