spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info
    password: H9MvYSqY3JmAC4aj
    username: root
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        max-wait: 30000
        min-idle: 0
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /api/v1
  port: 8080

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

qsbk:
  login:
    enable-sms: true
    expire-in: 60
    user_login_state_last: 604800000
  token:
    expire-in: 100000000

